/**
 * GENERATED FILE — do not edit by hand.
 *
 * Generated by `scripts/sync-model-limits.mjs` from Cursor's published docs:
 *   context windows  https://cursor.com/docs/account/pricing/request-based-legacy.md
 *   pricing          https://cursor.com/docs/models-and-pricing.md
 *
 * Data last changed: 2026-08-03
 * (a sync that finds no data change leaves this date alone, so it dates the
 *  last change to the generated maps — NOT the last time they were verified.
 *  Verification runs on a schedule in CI; see the model-data-drift job.)
 * Regenerate: `npm run sync:model-limits`
 *
 * Only MODEL_CONTEXT_LIMITS and MODEL_COST are derived from the docs.
 * MODEL_OUTPUT_LIMITS further down is hand-maintained, because Cursor's docs
 * publish no output-token column — but it is still emitted from this file's
 * template, so edit it in `scripts/sync-model-limits.mjs`, not here. An edit
 * made here is reverted by the next sync.
 *
 * Pricing is read from the structured Input / Cache write / Cache read /
 * Output columns only. The `Notes` cell is deliberately NOT parsed, even
 * though promotions are announced there in prose (Claude Sonnet 5's row
 * advertises "$2/M input and $10/M output through August 31, 2026" while its
 * price columns still read $3 / $15). Extracting money from free text is
 * confidently wrong by construction, promo windows expire, and Cursor's own
 * `agent.getUsage()` -> `chargedCents` is the authoritative source for
 * promotions, discounts, the Cursor Token Fee, and Max Mode multipliers. This
 * map is only the rate card opencode multiplies token counts by.
 */

/**
 * Per-model default context window limits (tokens), keyed by model id prefix.
 * The "Max context" column (1M for frontier models) requires Max Mode and is
 * NOT used here — the plugin can't detect Max Mode, so the default window is
 * the honest limit to display.
 *
 * Longest prefix wins: `claude-opus-4-8` (300K) beats `claude-opus-4` (200K).
 */
const MODEL_CONTEXT_LIMITS: Record<string, number> = {
  "auto-smart": 200_000,
  "claude-fable-5": 300_000,
  "claude-haiku-4-5": 200_000,
  "claude-opus-4-5": 200_000,
  "claude-opus-4-6": 200_000,
  "claude-opus-4-7": 300_000,
  "claude-opus-4-8": 300_000,
  "claude-opus-5": 300_000,
  "claude-sonnet-4": 200_000,
  "claude-sonnet-4-5": 200_000,
  "claude-sonnet-4-6": 200_000,
  "claude-sonnet-5": 200_000,
  "composer-2": 200_000,
  "composer-2.5": 200_000,
  "default": 200_000,
  "gemini-2.5-flash": 200_000,
  "gemini-3-flash": 200_000,
  "gemini-3.1-pro": 200_000,
  "gemini-3.5-flash": 200_000,
  "gemini-3.6-flash": 200_000,
  "glm-5.2": 200_000,
  "gpt-5-mini": 272_000,
  "gpt-5.1": 272_000,
  "gpt-5.2": 272_000,
  "gpt-5.3-codex": 272_000,
  "gpt-5.4": 272_000,
  "gpt-5.4-mini": 272_000,
  "gpt-5.4-nano": 272_000,
  "gpt-5.5": 272_000,
  "gpt-5.6-luna": 272_000,
  "gpt-5.6-sol": 272_000,
  "gpt-5.6-terra": 272_000,
  "grok-4.5": 256_000,
};

const DEFAULT_CONTEXT_LIMIT = 200_000;

/**
 * Sentinel `limit.input` that pushes opencode's auto-compaction threshold out
 * of reach, so auto-compaction never fires. opencode computes the threshold as
 * `limit.input ? limit.input - reserved : limit.context - maxOutput`, so a huge
 * `input` makes it unreachable while `limit.context` stays honest — the TUI
 * context gauge keeps working.
 *
 * Why suppress it: the Cursor agent runtime self-compacts on its own context
 * threshold (`@cursor/sdk` `dist/esm/357.js`, `preCompact` hook with
 * `trigger: "auto"`), so opencode-driven compaction is redundant. It is also
 * harmful — each opencode compaction rewrites the transcript, which classifies
 * as `divergence` and mints a fresh Cursor agentId, and every distinct agentId
 * permanently adds a guarded SQLite `store.db`/`-wal`/`-shm` triple that
 * `agent.close()` cannot release.
 *
 * This is NOT a real model capability. Verified against the opencode 1.18.11
 * binary by enumerating the call sites of `Is()` (the threshold function) rather
 * than textual hits on `limit.input`, since consumers reach it transitively:
 *   - `vl()`         — the proactive auto-compaction trigger. Suppressed here.
 *   - `Pd()`         — preserve-recent-tokens budget, also used by manual
 *                      `/compact`. Inert: it is `min(8000, max(2000,
 *                      floor(Is*0.25)))`, which saturates at 8000 for any
 *                      `Is >= 32000` — true both before and after the sentinel.
 * Everything else that touches `limit.input` is catalog merge/serialization.
 *
 * Also verified end-to-end (isolated HOME, `opencode models cursor --verbose`)
 * that a config-channel `limit.input` survives validation and reaches
 * `Provider.list()` with `limit.context` intact.
 *
 * Caveat: `Is()` is `max(0, input - reserved)`, so a user setting
 * `compaction.reserved >= this value` would drive the threshold to 0 and make
 * compaction fire every turn. Absurd but user-settable.
 */
export const NO_AUTO_COMPACTION_INPUT_LIMIT = 1_000_000_000;

/**
 * Resolve a model's context window by longest-prefix match against
 * {@link MODEL_CONTEXT_LIMITS}. Falls back to 200K for unknown models.
 */
export function resolveContextLimit(modelId: string): number {
  let best: number | undefined;
  let bestLen = 0;
  for (const [prefix, limit] of Object.entries(MODEL_CONTEXT_LIMITS)) {
    if (modelId.startsWith(prefix) && prefix.length > bestLen) {
      best = limit;
      bestLen = prefix.length;
    }
  }
  return best ?? DEFAULT_CONTEXT_LIMIT;
}

/**
 * Per-model API pricing (USD per million tokens), keyed by model id prefix.
 * Cursor Models pool models (Grok 4.5, Composer, Auto) have $0 — they draw
 * from the Cursor Models pool, not the Other Models pool, so there is no
 * per-token API charge and they are absent from the pricing docs entirely.
 *
 * Longest prefix wins: `gpt-5.4-mini` (0.75) beats `gpt-5.4` (2.50).
 */
const MODEL_COST: Record<string, { input: number; output: number; cacheRead: number; cacheWrite: number }> = {
  "auto-smart": { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  "claude-fable-5": { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
  "claude-haiku-4-5": { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 },
  "claude-opus-4-5": { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "claude-opus-4-6": { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "claude-opus-4-7": { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "claude-opus-4-8": { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "claude-opus-5": { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "claude-sonnet-4": { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
  "claude-sonnet-4-5": { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
  "claude-sonnet-4-6": { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
  "claude-sonnet-5": { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
  "composer-2": { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  "composer-2.5": { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  "default": { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  "gemini-2.5-flash": { input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0 },
  "gemini-3-flash": { input: 0.5, output: 3, cacheRead: 0.05, cacheWrite: 0 },
  "gemini-3.1-pro": { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 0 },
  "gemini-3.5-flash": { input: 1.5, output: 9, cacheRead: 0.15, cacheWrite: 0 },
  "gemini-3.6-flash": { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 },
  "glm-5.2": { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
  "gpt-5-mini": { input: 0.25, output: 2, cacheRead: 0.025, cacheWrite: 0 },
  "gpt-5.1": { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 },
  "gpt-5.2": { input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 },
  "gpt-5.3-codex": { input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 },
  "gpt-5.4": { input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 0 },
  "gpt-5.4-mini": { input: 0.75, output: 4.5, cacheRead: 0.075, cacheWrite: 0 },
  "gpt-5.4-nano": { input: 0.2, output: 1.25, cacheRead: 0.02, cacheWrite: 0 },
  "gpt-5.5": { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
  "gpt-5.6-luna": { input: 0.2, output: 1.2, cacheRead: 0.02, cacheWrite: 0.25 },
  "gpt-5.6-sol": { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 },
  "gpt-5.6-terra": { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 2.5 },
  "grok-4.5": { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
};

const DEFAULT_COST = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 };

/**
 * Resolve a model's per-token cost by longest-prefix match against
 * {@link MODEL_COST}. Falls back to $0 for unknown models (treated as
 * subscription/Cursor Models pool).
 */
export function resolveCost(modelId: string): {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
} {
  let best: { input: number; output: number; cacheRead: number; cacheWrite: number } | undefined;
  let bestLen = 0;
  for (const [prefix, cost] of Object.entries(MODEL_COST)) {
    if (modelId.startsWith(prefix) && prefix.length > bestLen) {
      best = cost;
      bestLen = prefix.length;
    }
  }
  return best ?? DEFAULT_COST;
}

/**
 * NOT DERIVED FROM THE DOCS — hand-maintained in the template inside
 * `scripts/sync-model-limits.mjs`. Cursor's docs publish no output-token
 * column, so there is nothing to generate these from. Editing this map here
 * has no lasting effect; the next sync reverts it.
 *
 * Per-model output token limits, keyed by model id prefix. The Cursor SDK
 * doesn't expose output limits, so these are best-known values. 32K default
 * (the previous hardcoded value); 64K for frontier models known to support
 * higher output. Low priority — the TUI doesn't display output limit.
 */
const MODEL_OUTPUT_LIMITS: Record<string, number> = {
  "claude-opus-4-7": 64_000,
  "claude-opus-4-8": 64_000,
  "claude-opus-5": 64_000,
  "claude-fable-5": 64_000,
  "gpt-5.5": 64_000,
  "gpt-5.6-sol": 64_000,
};

const DEFAULT_OUTPUT_LIMIT = 32_000;

/**
 * Resolve a model's output limit by longest-prefix match. Falls back to 32K.
 */
export function resolveOutputLimit(modelId: string): number {
  let best: number | undefined;
  let bestLen = 0;
  for (const [prefix, limit] of Object.entries(MODEL_OUTPUT_LIMITS)) {
    if (modelId.startsWith(prefix) && prefix.length > bestLen) {
      best = limit;
      bestLen = prefix.length;
    }
  }
  return best ?? DEFAULT_OUTPUT_LIMIT;
}
