import {
	mkdirSync,
	writeFileSync,
	readFileSync,
	existsSync,
	rmSync,
	readdirSync,
	statSync,
	copyFileSync,
	realpathSync,
} from "node:fs";
import type { Dirent } from "node:fs";
import { join, relative, dirname } from "node:path";
import { entryKind } from "../plugin/skill-discovery.js";
import type { DiscoveredSkill } from "../plugin/skill-discovery.js";

/** Location of the generated mirror, relative to the agent's cwd. */
const SKILLS_DIR = join(".cursor", "skills");
const IGNORE_FILE = ".gitignore";

/**
 * Frontmatter sentinel marking mirrored skills as generated by this plugin.
 * Only directories whose `SKILL.md` carries it are ever overwritten or
 * deleted, so a user-owned `.cursor/skills/<id>` is never clobbered.
 */
const SENTINEL = "generated: opencode-cursor";

/** Max bytes per individual supporting file (skip oversized files, not the whole skill). */
const MAX_FILE_BYTES = 1_048_576; // 1 MB

/** Max total mirrored bytes across all skills. */
const MAX_TOTAL_BYTES = 10_485_760; // 10 MB

/** Outcome of a {@link writeSkillMirror} attempt. */
export type SkillMirrorWrite =
	/** One or more skill directories were created or updated. */
	| "written"
	/** All skills already mirrored with identical content; no writes. */
	| "unchanged"
	/** No skills to mirror. */
	| "empty"
	/** A write error occurred; some skills may be unavailable. */
	| "partial";

/** True when the file carries the generated-by sentinel in its frontmatter. */
function isGenerated(content: string): boolean {
	if (!content.startsWith("---")) return false;
	const end = content.indexOf("\n---", 3);
	const frontmatter = end === -1 ? content : content.slice(0, end);
	return frontmatter.split(/\r?\n/).includes(SENTINEL);
}

/** Inject the sentinel into frontmatter, preserving name and description. */
function stampSentinel(content: string): string {
	if (!content.startsWith("---")) {
		// No frontmatter at all — shouldn't happen (discovery requires it),
		// but handle gracefully by wrapping the whole content.
		return `---\n${SENTINEL}\n---\n\n${content}`;
	}
	const end = content.indexOf("\n---", 3);
	if (end === -1) {
		return `---\n${SENTINEL}\n${content.slice(3)}`;
	}
	const frontmatter = content.slice(3, end);
	// Already has the sentinel — return as-is.
	if (frontmatter.includes(SENTINEL)) return content;
	// Insert sentinel before the closing ---.
	return `---${frontmatter}\n${SENTINEL}\n${content.slice(end)}`;
}

/** Recursively copy a file tree, skipping oversized files. Returns bytes copied + skipped files. */
function copyTree(
	srcDir: string,
	destDir: string,
	skillId: string,
	maxBytes: number,
	warn: (message: string) => void,
): { bytes: number; skipped: string[] } {
	let bytes = 0;
	const skipped: string[] = [];
	// Following symlinked directories admits cycles; track resolved paths.
	const visited = new Set<string>();

	function walk(src: string, dest: string) {
		let realSrc: string;
		try {
			realSrc = realpathSync(src);
		} catch {
			return;
		}
		if (visited.has(realSrc)) return;
		visited.add(realSrc);
		let entries;
		try {
			entries = readdirSync(src, { withFileTypes: true });
		} catch {
			return;
		}
		for (const entry of entries) {
			const srcPath = join(src, entry.name);
			const destPath = join(dest, entry.name);
			const kind = entryKind(entry, srcPath);
			if (kind === "dir") {
				walk(srcPath, destPath);
			} else if (kind === "file") {
				// Never copy SKILL.md here — it's already written with the
				// sentinel stamped by the caller. Copying the original would
				// overwrite the stamped version.
				if (entry.name === "SKILL.md") continue;
				try {
					const size = statSync(srcPath).size;
					if (size > MAX_FILE_BYTES) {
						skipped.push(relative(srcDir, srcPath));
						warn(
							`Skill "${skillId}": skipped oversized file "${relative(srcDir, srcPath)}" (${size} bytes > ${MAX_FILE_BYTES} limit). The rest of the skill is still mirrored.`,
						);
						continue;
					}
					if (bytes + size > maxBytes) {
						skipped.push(relative(srcDir, srcPath));
						warn(
							`Skill "${skillId}": skipped file "${relative(srcDir, srcPath)}" because the mirror's ${MAX_TOTAL_BYTES}-byte total size limit would be exceeded.`,
						);
						continue;
					}
					mkdirSync(dirname(destPath), { recursive: true });
					copyFileSync(srcPath, destPath);
					bytes += size;
				} catch {
					// Best effort — skip unreadable files.
				}
			}
		}
	}

	walk(srcDir, destDir);
	return { bytes, skipped };
}

/** Compare file contents and skip the write when unchanged. */
function writeIfChanged(path: string, content: string): boolean {
	const existing = existsSync(path) ? readFileSync(path, "utf8") : undefined;
	if (existing === content) return false;
	mkdirSync(dirname(path), { recursive: true });
	writeFileSync(path, content, "utf8");
	return true;
}

/**
 * Keep the generated skills out of git via `.cursor/skills/.gitignore` (which
 * also ignores itself so it doesn't pollute `git status`). Lists each mirrored
 * skill directory by id plus the `.gitignore` itself.
 */
function ensureGitIgnored(dir: string, skillIds: string[]): void {
	const path = join(dir, IGNORE_FILE);
	const existing = existsSync(path) ? readFileSync(path, "utf8") : "";
	const lines = existing.split(/\r?\n/);
	const missing = [...skillIds, IGNORE_FILE].filter(
		(entry) => !lines.includes(entry),
	);
	if (missing.length === 0) return;
	const prefix =
		existing && !existing.endsWith("\n") ? `${existing}\n` : existing;
	writeFileSync(path, `${prefix}${missing.join("\n")}\n`, "utf8");
}

/**
 * Materialise a git-ignored mirror of opencode's resolved skills into
 * `<cwd>/.cursor/skills/`, which Cursor discovers natively when the `project`
 * settings layer is loaded.
 *
 * Each skill is written to `<cwd>/.cursor/skills/<id>/SKILL.md` with a
 * `generated: opencode-cursor` sentinel stamped into the frontmatter.
 * Supporting files are copied alongside, preserving relative paths. A
 * user-owned skill directory (sentinel-less `SKILL.md`) is never overwritten —
 * it's skipped with a warning. Oversized individual files are skipped (not the
 * whole skill). Writes are idempotent (content compared before writing).
 * Sentinel-bearing directories for skills that no longer resolve are pruned.
 *
 * Never throws. Every failure degrades to "this skill is unavailable this
 * turn" plus a warning, mirroring how `resolveSystemDelivery` falls back.
 */
export function writeSkillMirror(
	cwd: string,
	skills: DiscoveredSkill[],
	warn: (message: string) => void,
): SkillMirrorWrite {
	if (skills.length === 0) {
		// Still prune stale sentinel-bearing dirs.
		try {
			pruneStale(cwd, new Set(), warn);
		} catch {
			// best effort
		}
		return "empty";
	}

	const dir = join(cwd, SKILLS_DIR);
	let totalBytes = 0;
	let wroteAny = false;
	let partial = false;
	const mirroredIds: string[] = [];

	for (const skill of skills) {
		if (totalBytes >= MAX_TOTAL_BYTES) {
			warn(
				`Skill mirror: total size limit (${MAX_TOTAL_BYTES} bytes) reached; skipping remaining skills: ${skills
					.filter((s) => !mirroredIds.includes(s.id))
					.map((s) => s.id)
					.join(", ")}`,
			);
			break;
		}

		const skillDir = join(dir, skill.id);
		const skillMdPath = join(skillDir, "SKILL.md");

		// Check for user-owned skill (sentinel-less SKILL.md).
		if (existsSync(skillMdPath)) {
			try {
				const existing = readFileSync(skillMdPath, "utf8");
				if (!isGenerated(existing)) {
					warn(
						`.cursor/skills/${skill.id}/SKILL.md exists but was not generated by opencode-cursor; leaving it untouched and skipping this skill.`,
					);
					continue;
				}
			} catch {
				// Can't read — assume it's ours and proceed.
			}
		}

		try {
			// Read and stamp the SKILL.md.
			const sourceContent = readFileSync(
				join(skill.sourceDir, "SKILL.md"),
				"utf8",
			);
			const stamped = stampSentinel(sourceContent);
			const skillMdBytes = Buffer.byteLength(stamped);
			if (totalBytes + skillMdBytes > MAX_TOTAL_BYTES) {
				warn(
					`Skill mirror: total size limit (${MAX_TOTAL_BYTES} bytes) reached; skipping skill "${skill.id}" and all remaining skills.`,
				);
				partial = true;
				break;
			}
			const changed = writeIfChanged(skillMdPath, stamped);
			if (changed) wroteAny = true;
			totalBytes += skillMdBytes;

			// Copy supporting files.
			const { bytes, skipped } = copyTree(
					skill.sourceDir,
					skillDir,
					skill.id,
					MAX_TOTAL_BYTES - totalBytes,
					warn,
				);
			totalBytes += bytes;
			if (skipped.length > 0) partial = true;

			mirroredIds.push(skill.id);
		} catch (error) {
			partial = true;
			warn(
				`Failed to mirror skill "${skill.id}": ${error instanceof Error ? error.message : String(error)}. This skill will be unavailable this turn.`,
			);
		}
	}

	// Prune stale sentinel-bearing dirs for skills no longer in the set.
	try {
		const staleRemoved = pruneStale(
			cwd,
			new Set(mirroredIds),
			warn,
		);
		if (staleRemoved) wroteAny = true;
	} catch {
		// best effort
	}

	// Update .gitignore with the current set of mirrored skill ids.
	if (mirroredIds.length > 0) {
		try {
			ensureGitIgnored(dir, mirroredIds);
		} catch {
			// non-fatal
		}
	}

	if (partial) return "partial";
	return wroteAny ? "written" : "unchanged";
}

/**
 * Remove sentinel-bearing skill directories for skills that no longer resolve.
 * User-owned directories (no sentinel) are left in place. Returns true if any
 * directories were removed.
 */
function pruneStale(
	cwd: string,
	currentIds: Set<string>,
	warn: (message: string) => void,
): boolean {
	const dir = join(cwd, SKILLS_DIR);
	if (!existsSync(dir)) return false;
	let removed = false;
	let entries: Dirent[];
	try {
		entries = readdirSync(dir, { withFileTypes: true });
	} catch {
		return false;
	}
	for (const entry of entries) {
		if (!entry.isDirectory()) continue;
		if (entry.name === "." || entry.name === "..") continue;
		if (currentIds.has(entry.name)) continue;
		const skillMdPath = join(dir, entry.name, "SKILL.md");
		if (!existsSync(skillMdPath)) continue;
		try {
			const content = readFileSync(skillMdPath, "utf8");
			if (isGenerated(content)) {
				rmSync(join(dir, entry.name), { recursive: true, force: true });
				removed = true;
			}
		} catch {
			// Can't read — leave it alone.
		}
	}
	return removed;
}

/**
 * Remove the entire generated skill mirror (best-effort); used on plugin
 * dispose. Only deletes directories whose `SKILL.md` carries the sentinel —
 * user-owned `.cursor/skills/<id>` directories are left in place. Also
 * removes the `.gitignore` if it was generated (contains the sentinel pattern).
 */
export function removeSkillMirror(cwd: string): void {
	const dir = join(cwd, SKILLS_DIR);
	if (!existsSync(dir)) return;
	try {
		const entries = readdirSync(dir, { withFileTypes: true });
		for (const entry of entries) {
			if (!entry.isDirectory()) continue;
			const skillMdPath = join(dir, entry.name, "SKILL.md");
			if (!existsSync(skillMdPath)) continue;
			try {
				if (isGenerated(readFileSync(skillMdPath, "utf8"))) {
					rmSync(join(dir, entry.name), { recursive: true, force: true });
				}
			} catch {
				// best effort
			}
		}
		// Remove the .gitignore if all sentinel dirs are gone.
		const remaining = readdirSync(dir, { withFileTypes: true });
		const hasSentinelDir = remaining.some((e) => {
			if (!e.isDirectory()) return false;
			const p = join(dir, e.name, "SKILL.md");
			if (!existsSync(p)) return false;
			try {
				return isGenerated(readFileSync(p, "utf8"));
			} catch {
				return false;
			}
		});
		if (!hasSentinelDir) {
			const ignorePath = join(dir, IGNORE_FILE);
			if (existsSync(ignorePath)) {
				try {
					rmSync(ignorePath);
				} catch {
					// best effort
				}
			}
		}
	} catch {
		// best effort — already gone or unreadable
	}
}

/**
 * Build the `<available_skills>` catalogue text for the system rule. Lists each
 * skill's id and description, plus a one-line instruction to load the matching
 * skill file before starting relevant work. Returns undefined when no skills
 * are mirrored (so the caller can skip appending an empty section).
 */
export function buildSkillsCatalogue(
	skills: DiscoveredSkill[],
): string | undefined {
	if (skills.length === 0) return undefined;
	const lines = skills.map(
		(s) => `- **${s.id}**: ${s.description}`,
	);
	return [
		"<available_skills>",
		"The following skills are available. Load the matching skill from `.cursor/skills/<id>/SKILL.md` before starting relevant work:",
		"",
		...lines,
		"</available_skills>",
	].join("\n");
}
