import {
	mkdirSync,
	writeFileSync,
	readFileSync,
	existsSync,
	rmSync,
} from "node:fs";
import { join } from "node:path";
import type { LanguageModelV3Prompt } from "@ai-sdk/provider";
import type { SettingSource } from "@cursor/sdk";
import type { SystemPromptMode } from "./message-map.js";

/** Location of the generated rule, relative to the agent's cwd. */
const RULES_DIR = join(".cursor", "rules");
const RULE_FILE = "opencode.mdc";
const IGNORE_FILE = ".gitignore";

/**
 * Frontmatter sentinel marking the rule as generated by this plugin. Only
 * files carrying it are ever overwritten or deleted, so a user-owned
 * `.cursor/rules/opencode.mdc` is never clobbered.
 */
const SENTINEL = "generated: opencode-cursor";

/** Concatenate every system-message body from an AI-SDK prompt (trimmed). */
export function extractSystemText(prompt: LanguageModelV3Prompt): string {
	const parts: string[] = [];
	for (const message of prompt) {
		if (message.role === "system") parts.push(message.content);
	}
	return parts.join("\n\n").trim();
}

/** Outcome of a {@link writeSystemRule} attempt. */
export type SystemRuleWrite =
	/** Rule file created or updated. */
	| "written"
	/** Existing generated rule already has this content; write skipped. */
	| "unchanged"
	/** No system text to deliver; nothing written. */
	| "empty"
	/** A user-owned (sentinel-less) opencode.mdc exists; left untouched. */
	| "blocked";

/** True when the file carries the generated-by sentinel in its frontmatter. */
function isGenerated(content: string): boolean {
	if (!content.startsWith("---")) return false;
	const end = content.indexOf("\n---", 3);
	const frontmatter = end === -1 ? content : content.slice(0, end);
	return frontmatter.split(/\r?\n/).includes(SENTINEL);
}

/**
 * Write opencode's system prompt to `<cwd>/.cursor/rules/opencode.mdc` as an
 * always-applied Cursor project rule. Cursor loads this through its authoritative
 * rules channel (`settingSources` including "project"), so opencode's controlling
 * instructions reach the agent without being flattened into the untrusted
 * user-message transcript (which injection-hardened models reject).
 *
 * The file carries a generated-by sentinel; a pre-existing sentinel-less file
 * is treated as user-owned and never overwritten ("blocked"). An existing
 * generated rule with identical content is left as-is ("unchanged") to keep
 * sync fs writes off the stream hot path. May throw on fs errors (read-only
 * checkout etc.) — callers should degrade gracefully.
 */
export function writeSystemRule(
	cwd: string,
	systemText: string,
): SystemRuleWrite {
	if (!systemText) return "empty";
	const dir = join(cwd, RULES_DIR);
	const path = join(dir, RULE_FILE);
	const body = `---\nalwaysApply: true\n${SENTINEL}\n---\n\n${systemText}\n`;
	const existing = existsSync(path) ? readFileSync(path, "utf8") : undefined;
	if (existing !== undefined) {
		if (!isGenerated(existing)) return "blocked";
		if (existing === body) return "unchanged";
	}
	mkdirSync(dir, { recursive: true });
	writeFileSync(path, body, "utf8");
	ensureGitIgnored(dir);
	return "written";
}

/**
 * Keep the generated rule out of git via `.cursor/rules/.gitignore` (which
 * also ignores itself so it doesn't pollute `git status`).
 */
function ensureGitIgnored(dir: string): void {
	const path = join(dir, IGNORE_FILE);
	const existing = existsSync(path) ? readFileSync(path, "utf8") : "";
	const lines = existing.split(/\r?\n/);
	const missing = [RULE_FILE, IGNORE_FILE].filter(
		(entry) => !lines.includes(entry),
	);
	if (missing.length === 0) return;
	const prefix =
		existing && !existing.endsWith("\n") ? `${existing}\n` : existing;
	writeFileSync(path, `${prefix}${missing.join("\n")}\n`, "utf8");
}

/**
 * Remove the generated rule (best-effort); used on plugin dispose. Only
 * deletes files carrying the generated-by sentinel — a user-owned
 * opencode.mdc is left in place.
 */
export function removeSystemRule(cwd: string): void {
	try {
		const path = join(cwd, RULES_DIR, RULE_FILE);
		if (isGenerated(readFileSync(path, "utf8"))) rmSync(path);
	} catch {
		// best effort — already gone or never written
	}
}

/** How the system prompt will be delivered for this turn. */
export interface SystemDelivery {
	mode: SystemPromptMode;
	settingSources: SettingSource[] | undefined;
}

/**
 * Decide how opencode's system prompt reaches the Cursor agent for one turn.
 *
 * In "rules" mode this writes the rule file and enables the `project`
 * settings layer — but ONLY when the user did not explicitly configure
 * `settingSources` without "project" (a deliberate hardening opt-out: the
 * project layer also loads the repo's `.cursor/mcp.json`, hooks, and other
 * rules). On an opt-out, a failed write (read-only checkout etc.), or a
 * user-owned rule file, it degrades to inline "message" delivery for the
 * turn and reports the reason via `warn`. Never throws.
 */
export function resolveSystemDelivery(options: {
	mode: SystemPromptMode;
	settingSources: SettingSource[] | undefined;
	cwd: string;
	systemText: string;
	warn: (message: string) => void;
}): SystemDelivery {
	const { mode, settingSources, cwd, systemText, warn } = options;
	if (mode !== "rules") return { mode, settingSources };
	if (settingSources && !settingSources.includes("project")) {
		warn(
			'systemPrompt "rules" needs the "project" settings layer, but settingSources was explicitly configured without it; delivering the system prompt inline ("message" mode) instead. Add "project" to settingSources or set systemPrompt: "message" to silence this.',
		);
		return { mode: "message", settingSources };
	}
	let result: SystemRuleWrite;
	try {
		result = writeSystemRule(cwd, systemText);
	} catch (error) {
		warn(
			`failed to write .cursor/rules/${RULE_FILE} (${error instanceof Error ? error.message : String(error)}); delivering the system prompt inline ("message" mode) for this turn.`,
		);
		return { mode: "message", settingSources };
	}
	if (result === "blocked") {
		warn(
			`.cursor/rules/${RULE_FILE} exists but was not generated by opencode-cursor; leaving it untouched and delivering the system prompt inline ("message" mode).`,
		);
		return { mode: "message", settingSources };
	}
	if (result === "empty") return { mode, settingSources };
	return { mode, settingSources: settingSources ?? ["project"] };
}
